server:
  port: 8085
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: demo_example
swagger4kafka.enabled: true
swagger4kafka.headers.sendBytes: true

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
  swagger-ui:
    enabled: true