server:
  port: 8085
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: demo_example

axenapi:
  kafka:
    swagger:
      enabled: true
  headers:
    sendBytes: true

springdoc:
  api-docs:
    enabled: true
    version: openapi_3_0
  swagger-ui:
    enabled: true