server:
  port: 8085
spring:
  kafka:
#    bootstrap-servers: localhost:29092
    consumer:
      group-id: demo_example

axenapi:
  kafka:
    swagger:
      enabled: true
  headers:
    sendBytes: true
my.bootstrap-servers: localhost:29092